### ISSUE TITLE
orgtbl-edit-save-function: Symbol’s function definition is void: export-file

### ISSUE THREAD

**Issue by fountainer** [shankar2k/orgtbl-edit#1]
When I try to save the buffer, the following error occurs.
```
orgtbl-edit-save-function: Symbol’s function definition is void: export-file
```

**Comment by shankar2k** [comment]
I pushed a commit that fixes some minor bugs, but I wasn't able to replicate your error. What version of Emacs and Org are you using? Can you try it again using the minimal config file test-orgtbl-edit.el below (run `emacs -Q --load test-orgtbl-edit.el`)?

```
;; change ~/lisp to wherever orgtbl-edit is located on your machine
(add-to-list 'load-path "~/lisp/orgtbl-edit") 
(require 'orgtbl-edit)
```

**Comment by fountainer** [comment]
When I test this package using the minimal configuration, there is no error. I don't know which settings cause this problem. Here is the traceback information:
```
Debugger entered--Lisp error: (void-function export-file)
  export-file("~/Downloads/main_20211106_dj30.csv")
  orgtbl-edit-save-function()
  run-hook-with-args-until-success(orgtbl-edit-save-function)
  basic-save-buffer(t)
  save-buffer(1)
  funcall-interactively(save-buffer 1)
  call-interactively(save-buffer nil nil)
  command-execute(save-buffer)
```

The Emacs version is `GNU Emacs 27.2 (build 1, x86_64-apple-darwin20.6.0, Carbon Version 164 AppKit 2022.6)
 of 2021-09-19` and the org version is `Org mode version 9.6 (9.6-??-d3836c1a1 @ /Users/sfq/.my.emacs.d/doom-emacs/.emacs.d/.local/straight/build-27.2/org/).`

**Comment by fountainer** [comment]
I tried the version with the latest commit. It works.

**Comment by shankar2k** [comment]
That's good to hear. I'm surprised that it works with the latest commit, because I didn't make any changes that address your error. Looking at the debug trace, my guess is that doom or some other part of your configuration was misinterpreting the if-let* macro I was using, and so was trying to execute `(export-function ...)` as a function call instead of a let assignment.

If it's alright with you I'll close this issue.
